[package]
name = "epics-sys"
version = "0.1.1"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2018"
documentation = "https://binp-automation.github.io/epics-sys/target/doc/epics_sys/"

[dependencies]

[build-dependencies]
bindgen = "0.49.2"
